version: "3.4"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  mysql:
    image: mysql:8.0.34
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'edisoncsi'
      MYSQL_PASSWORD: 'Edisoncsi84$$'
      MYSQL_ROOT_PASSWORD: 'Edisoncsi84$$'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
  mongodb:
    image: mongo:5.0.20
    environment:
      MONGO_INITDB_ROOT_USERNAME: "edisoncsi"
      MONGO_INITDB_ROOT_PASSWORD: "Edisoncsi84$$"
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mysql_data:
    driver: local
  mongodb_data:
    driver: local
networks:
  default:
    name: bankingNet
